// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_time(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_rng_state(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_alloc(SEXP r_pars, SEXP r_time_start, SEXP r_time, SEXP r_time_control, SEXP r_data, SEXP r_n_particles, SEXP r_n_groups, SEXP r_n_threads, SEXP r_seed) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time_start), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_system_plague_stochastic_humans_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_humans_compare_data(SEXP ptr, SEXP r_data, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_humans_compare_data(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_data), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP r_index_state, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_unfilter_plague_stochastic_humans_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_unfilter_plague_stochastic_humans_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_unfilter_plague_stochastic_humans_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_update_pars(SEXP ptr, SEXP r_pars, SEXP r_index_group) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_run(SEXP ptr, SEXP r_initial, SEXP save_trajectories, SEXP save_snapshots, SEXP adjoint, SEXP index_state, SEXP index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_run(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_initial), cpp11::as_cpp<cpp11::decay_t<bool>>(save_trajectories), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(save_snapshots), cpp11::as_cpp<cpp11::decay_t<bool>>(adjoint), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_last_trajectories(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_last_trajectories(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_last_snapshots(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_last_snapshots(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_last_state(SEXP ptr, SEXP select_random_particle, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_last_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<bool>>(select_random_particle), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_rng_state(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_humans.cpp
SEXP dust2_filter_plague_stochastic_humans_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _yersinia_dust2_filter_plague_stochastic_humans_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_filter_plague_stochastic_humans_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_alloc(SEXP r_pars, SEXP r_time, SEXP r_time_control, SEXP r_n_particles, SEXP r_n_groups, SEXP r_seed, SEXP r_deterministic, SEXP r_n_threads) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_alloc(cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_pars), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_time_control), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_particles), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_groups), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_seed), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_deterministic), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_n_threads)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_run_to_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_run_to_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_state(SEXP ptr, SEXP r_index_state, SEXP r_index_particle, SEXP r_index_group, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_particle), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_group), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_time(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_time(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_set_state_initial(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_set_state_initial(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_set_state_initial(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_set_state(cpp11::sexp ptr, cpp11::list r_state);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_set_state(SEXP ptr, SEXP r_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_set_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(r_state)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_reorder(cpp11::sexp ptr, cpp11::integers r_index);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_reorder(SEXP ptr, SEXP r_index) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_reorder(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(r_index)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_rng_state(cpp11::sexp ptr);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_rng_state(SEXP ptr) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_set_rng_state(SEXP ptr, SEXP r_rng_state) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_set_rng_state(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_rng_state)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_set_time(cpp11::sexp ptr, cpp11::sexp r_time);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_set_time(SEXP ptr, SEXP r_time) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_set_time(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_time)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_update_pars(cpp11::sexp ptr, cpp11::list pars);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_update_pars(SEXP ptr, SEXP pars) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_update_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(pars)));
  END_CPP11
}
// plague_stochastic_metapop.cpp
SEXP dust2_system_plague_stochastic_metapop_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension);
extern "C" SEXP _yersinia_dust2_system_plague_stochastic_metapop_simulate(SEXP ptr, SEXP r_times, SEXP r_index_state, SEXP preserve_particle_dimension, SEXP preserve_group_dimension) {
  BEGIN_CPP11
    return cpp11::as_sexp(dust2_system_plague_stochastic_metapop_simulate(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(ptr), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_times), cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_index_state), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_particle_dimension), cpp11::as_cpp<cpp11::decay_t<bool>>(preserve_group_dimension)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_yersinia_dust2_filter_plague_stochastic_humans_alloc",               (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_alloc,               9},
    {"_yersinia_dust2_filter_plague_stochastic_humans_last_snapshots",      (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_last_snapshots,      4},
    {"_yersinia_dust2_filter_plague_stochastic_humans_last_state",          (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_last_state,          4},
    {"_yersinia_dust2_filter_plague_stochastic_humans_last_trajectories",   (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_last_trajectories,   4},
    {"_yersinia_dust2_filter_plague_stochastic_humans_rng_state",           (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_rng_state,           1},
    {"_yersinia_dust2_filter_plague_stochastic_humans_run",                 (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_run,                 9},
    {"_yersinia_dust2_filter_plague_stochastic_humans_set_rng_state",       (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_set_rng_state,       2},
    {"_yersinia_dust2_filter_plague_stochastic_humans_update_pars",         (DL_FUNC) &_yersinia_dust2_filter_plague_stochastic_humans_update_pars,         3},
    {"_yersinia_dust2_system_plague_stochastic_humans_alloc",               (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_alloc,               8},
    {"_yersinia_dust2_system_plague_stochastic_humans_compare_data",        (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_compare_data,        4},
    {"_yersinia_dust2_system_plague_stochastic_humans_reorder",             (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_reorder,             2},
    {"_yersinia_dust2_system_plague_stochastic_humans_rng_state",           (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_rng_state,           1},
    {"_yersinia_dust2_system_plague_stochastic_humans_run_to_time",         (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_run_to_time,         2},
    {"_yersinia_dust2_system_plague_stochastic_humans_set_rng_state",       (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_set_rng_state,       2},
    {"_yersinia_dust2_system_plague_stochastic_humans_set_state",           (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_set_state,           2},
    {"_yersinia_dust2_system_plague_stochastic_humans_set_state_initial",   (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_set_state_initial,   1},
    {"_yersinia_dust2_system_plague_stochastic_humans_set_time",            (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_set_time,            2},
    {"_yersinia_dust2_system_plague_stochastic_humans_simulate",            (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_simulate,            5},
    {"_yersinia_dust2_system_plague_stochastic_humans_state",               (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_state,               6},
    {"_yersinia_dust2_system_plague_stochastic_humans_time",                (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_time,                1},
    {"_yersinia_dust2_system_plague_stochastic_humans_update_pars",         (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_humans_update_pars,         2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_alloc",              (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_alloc,              8},
    {"_yersinia_dust2_system_plague_stochastic_metapop_reorder",            (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_reorder,            2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_rng_state",          (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_rng_state,          1},
    {"_yersinia_dust2_system_plague_stochastic_metapop_run_to_time",        (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_run_to_time,        2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_set_rng_state",      (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_set_rng_state,      2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_set_state",          (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_set_state,          2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_set_state_initial",  (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_set_state_initial,  1},
    {"_yersinia_dust2_system_plague_stochastic_metapop_set_time",           (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_set_time,           2},
    {"_yersinia_dust2_system_plague_stochastic_metapop_simulate",           (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_simulate,           5},
    {"_yersinia_dust2_system_plague_stochastic_metapop_state",              (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_state,              6},
    {"_yersinia_dust2_system_plague_stochastic_metapop_time",               (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_time,               1},
    {"_yersinia_dust2_system_plague_stochastic_metapop_update_pars",        (DL_FUNC) &_yersinia_dust2_system_plague_stochastic_metapop_update_pars,        2},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_alloc",             (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_alloc,             8},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_last_snapshots",    (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_last_snapshots,    4},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_last_state",        (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_last_state,        4},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_last_trajectories", (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_last_trajectories, 4},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_run",               (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_run,               9},
    {"_yersinia_dust2_unfilter_plague_stochastic_humans_update_pars",       (DL_FUNC) &_yersinia_dust2_unfilter_plague_stochastic_humans_update_pars,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_yersinia(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
