// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.45) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(plague_ode_min)]]
// [[dust2::time_type(continuous)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(K_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(K_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I_ini, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(delta_R, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(kappa, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(p_obs, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(lambda_baseline, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(w_time, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(w_value, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
class plague_ode_min {
public:
  plague_ode_min() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 6> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> w_time;
      dust2::array::dimensions<1> w_value;
    } dim;
    real_type K_r;
    real_type K_h;
    real_type I_ini;
    real_type beta_r;
    real_type beta_h;
    real_type rho;
    real_type m_r;
    real_type m_h;
    real_type g_r;
    real_type g_h;
    real_type delta_R;
    real_type kappa;
    real_type p_obs;
    real_type lambda_baseline;
    std::vector<real_type> w_time;
    std::vector<real_type> w_value;
    dust2::interpolate::InterpolateLinear<real_type> interpolate_w_beta;
  };
  struct internal_state {};
  struct data_type {
    real_type deaths;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type K_r = dust2::r::read_real(parameters, "K_r", 2500);
    const real_type K_h = dust2::r::read_real(parameters, "K_h", 5000);
    const real_type I_ini = dust2::r::read_real(parameters, "I_ini", 5);
    const real_type beta_r = dust2::r::read_real(parameters, "beta_r", static_cast<real_type>(0.5));
    const real_type beta_h = dust2::r::read_real(parameters, "beta_h", static_cast<real_type>(0.02));
    const real_type rho = dust2::r::read_real(parameters, "rho", static_cast<real_type>(2.5));
    const real_type m_r = dust2::r::read_real(parameters, "m_r", static_cast<real_type>(0.20000000000000001));
    const real_type m_h = dust2::r::read_real(parameters, "m_h", static_cast<real_type>(0.080000000000000002));
    const real_type g_r = dust2::r::read_real(parameters, "g_r", 0);
    const real_type g_h = dust2::r::read_real(parameters, "g_h", static_cast<real_type>(0.10000000000000001));
    const real_type delta_R = dust2::r::read_real(parameters, "delta_R", static_cast<real_type>(0.20000000000000001));
    const real_type kappa = dust2::r::read_real(parameters, "kappa", 15);
    const real_type p_obs = dust2::r::read_real(parameters, "p_obs", static_cast<real_type>(0.80000000000000004));
    const real_type lambda_baseline = dust2::r::read_real(parameters, "lambda_baseline", 1);
    dim.w_time = dust2::r::read_dimensions<1>(parameters, "w_time");
    dim.w_value = dust2::r::read_dimensions<1>(parameters, "w_value");
    std::vector<real_type> w_time(dim.w_time.size);
    dust2::r::read_real_array(parameters, dim.w_time, w_time.data(), "w_time", true);
    std::vector<real_type> w_value(dim.w_value.size);
    dust2::r::read_real_array(parameters, dim.w_value, w_value.data(), "w_value", true);
    const auto interpolate_w_beta = dust2::interpolate::InterpolateLinear(w_time, w_value, "w_time", "w_value");
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"I", {}},
      {"Q", {}},
      {"S_h", {}},
      {"I_h", {}},
      {"D_h", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, K_r, K_h, I_ini, beta_r, beta_h, rho, m_r, m_h, g_r, g_h, delta_R, kappa, p_obs, lambda_baseline, w_time, w_value, interpolate_w_beta};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto deaths = dust2::r::read_real(data, "deaths", NA_REAL);
    return data_type{deaths};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.K_r = dust2::r::read_real(parameters, "K_r", shared.K_r);
    shared.K_h = dust2::r::read_real(parameters, "K_h", shared.K_h);
    shared.I_ini = dust2::r::read_real(parameters, "I_ini", shared.I_ini);
    shared.beta_r = dust2::r::read_real(parameters, "beta_r", shared.beta_r);
    shared.beta_h = dust2::r::read_real(parameters, "beta_h", shared.beta_h);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.m_r = dust2::r::read_real(parameters, "m_r", shared.m_r);
    shared.m_h = dust2::r::read_real(parameters, "m_h", shared.m_h);
    shared.g_r = dust2::r::read_real(parameters, "g_r", shared.g_r);
    shared.g_h = dust2::r::read_real(parameters, "g_h", shared.g_h);
    shared.delta_R = dust2::r::read_real(parameters, "delta_R", shared.delta_R);
    shared.kappa = dust2::r::read_real(parameters, "kappa", shared.kappa);
    shared.p_obs = dust2::r::read_real(parameters, "p_obs", shared.p_obs);
    shared.lambda_baseline = dust2::r::read_real(parameters, "lambda_baseline", shared.lambda_baseline);
    dust2::r::read_real_array(parameters, shared.dim.w_time, shared.w_time.data(), "w_time", false);
    dust2::r::read_real_array(parameters, shared.dim.w_value, shared.w_value.data(), "w_value", false);
    shared.interpolate_w_beta = dust2::interpolate::InterpolateLinear(shared.w_time, shared.w_value, "w_time", "w_value");
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = shared.K_r - shared.I_ini;
    state[1] = shared.I_ini;
    state[2] = 0;
    state[3] = shared.K_h;
    state[4] = 0;
    state[5] = 0;
  }
  static void rhs(real_type time, const real_type* state, const shared_state& shared, internal_state& internal, real_type* state_deriv) {
    const auto S = state[0];
    const auto I = state[1];
    const auto Q = state[2];
    const auto S_h = state[3];
    const auto I_h = state[4];
    const real_type T_r = S + I;
    const real_type pref = monty::math::exp<real_type>(-shared.rho * T_r / shared.K_r);
    const real_type w_beta = shared.interpolate_w_beta.eval(time);
    const real_type lambda_r = shared.beta_r * w_beta * Q * (1 - pref) / T_r;
    const real_type lambda_h = shared.beta_h * w_beta * Q * pref / shared.K_r;
    state_deriv[0] = -lambda_r * S;
    state_deriv[1] = lambda_r * S - shared.m_r * I;
    state_deriv[2] = shared.m_r * I * (1 - shared.g_r) - shared.delta_R * Q;
    state_deriv[3] = -lambda_h * S_h;
    state_deriv[4] = lambda_h * S_h - shared.m_h * I_h;
    state_deriv[5] = shared.m_h * I_h * (1 - shared.g_h);
  }
  static auto zero_every(const shared_state& shared) {
    return dust2::zero_every_type<real_type>{{1, {5}}};
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto D_h = state[5];
    real_type odin_ll = 0;
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.deaths, shared.kappa, shared.p_obs * D_h + shared.lambda_baseline, true));
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/continuous/system.hpp>
#include <dust2/r/continuous/filter.hpp>
#include <dust2/r/continuous/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_continuous_alloc<plague_ode_min>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_internals(cpp11::sexp ptr, bool include_coefficients, bool include_history) {
  return dust2::r::dust2_system_internals<dust2::dust_continuous<plague_ode_min>>(ptr, include_coefficients, include_history);
}
[[cpp11::register]]
SEXP dust2_system_plague_ode_min_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_continuous<plague_ode_min>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_continuous<plague_ode_min>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_continuous<plague_ode_min>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_continuous<plague_ode_min>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_continuous<plague_ode_min>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_continuous<plague_ode_min>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_continuous<plague_ode_min>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_continuous<plague_ode_min>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_continuous<plague_ode_min>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_continuous<plague_ode_min>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_plague_ode_min_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_continuous<plague_ode_min>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_continuous_unfilter_alloc<plague_ode_min>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_continuous_filter_alloc<plague_ode_min>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_plague_ode_min_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_continuous<plague_ode_min>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_continuous<plague_ode_min>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_continuous<plague_ode_min>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_ode_min_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_continuous<plague_ode_min>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_continuous<plague_ode_min>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_continuous<plague_ode_min>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_continuous<plague_ode_min>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_plague_ode_min_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_continuous<plague_ode_min>>(ptr, r_rng_state);
}
