// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.45) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(plague_stochastic_metapop)]]
// [[dust2::time_type(discrete)]]
// [[dust2::parameter(npop, type = "int", rank = 0, required = FALSE, constant = TRUE)]]
// [[dust2::parameter(tau, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(mu_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(contact_r, type = "real_type", rank = 2, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(K_r, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(K_h, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I_ini, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(R_ini, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(I_h_ini, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(R_h_ini, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
// [[dust2::parameter(r_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(r_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(p, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(d_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(d_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_I, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(delta_R, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(iota, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(obs_period, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(seasonal, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
class plague_stochastic_metapop {
public:
  plague_stochastic_metapop() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 9> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> S;
      dust2::array::dimensions<1> I;
      dust2::array::dimensions<1> R;
      dust2::array::dimensions<1> Q;
      dust2::array::dimensions<1> D_r;
      dust2::array::dimensions<1> S_h;
      dust2::array::dimensions<1> I_h;
      dust2::array::dimensions<1> R_h;
      dust2::array::dimensions<1> D_h;
      dust2::array::dimensions<1> T_r;
      dust2::array::dimensions<1> rat_birth_rate_S;
      dust2::array::dimensions<1> rat_birth_rate_R;
      dust2::array::dimensions<1> rat_birth_rate_S_clipped;
      dust2::array::dimensions<1> rat_birth_rate_R_clipped;
      dust2::array::dimensions<1> lambda_r;
      dust2::array::dimensions<1> lambda_h;
      dust2::array::dimensions<1> lambda_hh;
      dust2::array::dimensions<1> p_SI_raw;
      dust2::array::dimensions<1> p_SI;
      dust2::array::dimensions<1> p_SI_h_raw;
      dust2::array::dimensions<1> p_SI_h;
      dust2::array::dimensions<1> p_rat_birth_S;
      dust2::array::dimensions<1> p_rat_birth_R;
      dust2::array::dimensions<1> n_deaths_S;
      dust2::array::dimensions<1> n_deaths_I;
      dust2::array::dimensions<1> n_deaths_R;
      dust2::array::dimensions<1> n_SI;
      dust2::array::dimensions<1> n_IR;
      dust2::array::dimensions<1> n_recovered;
      dust2::array::dimensions<1> n_births_S;
      dust2::array::dimensions<1> n_births_R;
      dust2::array::dimensions<1> n_resistant_births;
      dust2::array::dimensions<1> n_susceptible_births;
      dust2::array::dimensions<1> n_new_carcasses;
      dust2::array::dimensions<1> n_carcass_decay;
      dust2::array::dimensions<1> n_emigrate_S;
      dust2::array::dimensions<1> n_emigrate_I;
      dust2::array::dimensions<1> n_emigrate_R;
      dust2::array::dimensions<1> n_immigrate_S;
      dust2::array::dimensions<1> n_immigrate_I;
      dust2::array::dimensions<1> n_immigrate_R;
      dust2::array::dimensions<1> n_deaths_S_h;
      dust2::array::dimensions<1> n_deaths_I_h;
      dust2::array::dimensions<1> n_deaths_R_h;
      dust2::array::dimensions<1> births_h;
      dust2::array::dimensions<1> n_SI_h;
      dust2::array::dimensions<1> n_IR_h;
      dust2::array::dimensions<1> n_recovered_h;
      dust2::array::dimensions<1> initial_S;
      dust2::array::dimensions<1> initial_S_h;
      dust2::array::dimensions<1> K_r;
      dust2::array::dimensions<1> K_h;
      dust2::array::dimensions<1> I_ini;
      dust2::array::dimensions<1> R_ini;
      dust2::array::dimensions<1> I_h_ini;
      dust2::array::dimensions<1> R_h_ini;
      dust2::array::dimensions<2> contact_r;
      dust2::array::dimensions<2> sum_remaining_contact;
      dust2::array::dimensions<2> cond_p_r;
      dust2::array::dimensions<2> S_flow;
      dust2::array::dimensions<2> I_flow;
      dust2::array::dimensions<2> R_flow;
      dust2::array::dimensions<1> seasonal;
    } dim;
    int npop;
    real_type tau;
    real_type mu_r;
    real_type r_r;
    real_type r_h;
    real_type p;
    real_type d_r;
    real_type d_h;
    real_type beta_r;
    real_type beta_h;
    real_type beta_I;
    real_type rho;
    real_type m_r;
    real_type m_h;
    real_type g_r;
    real_type g_h;
    real_type delta_R;
    real_type iota;
    real_type obs_period;
    real_type p_IR;
    real_type p_rat_death;
    real_type p_migrate_r;
    real_type p_human_death;
    real_type birth_rate_h;
    real_type p_IR_h;
    std::vector<real_type> seasonal;
    real_type birth_rate_h_clipped;
    std::vector<real_type> contact_r;
    std::vector<real_type> K_r;
    std::vector<real_type> K_h;
    std::vector<real_type> I_ini;
    std::vector<real_type> R_ini;
    std::vector<real_type> I_h_ini;
    std::vector<real_type> R_h_ini;
    std::vector<real_type> sum_remaining_contact;
    real_type p_human_birth;
    std::vector<real_type> initial_S;
    std::vector<real_type> initial_S_h;
    std::vector<real_type> cond_p_r;
  };
  struct internal_state {
    std::vector<real_type> T_r;
    std::vector<real_type> n_deaths_S;
    std::vector<real_type> n_deaths_I;
    std::vector<real_type> n_deaths_R;
    std::vector<real_type> n_deaths_S_h;
    std::vector<real_type> n_deaths_I_h;
    std::vector<real_type> n_deaths_R_h;
    std::vector<real_type> rat_birth_rate_S;
    std::vector<real_type> rat_birth_rate_R;
    std::vector<real_type> lambda_r;
    std::vector<real_type> lambda_h;
    std::vector<real_type> lambda_hh;
    std::vector<real_type> n_IR;
    std::vector<real_type> n_emigrate_R;
    std::vector<real_type> n_IR_h;
    std::vector<real_type> rat_birth_rate_S_clipped;
    std::vector<real_type> rat_birth_rate_R_clipped;
    std::vector<real_type> p_SI_raw;
    std::vector<real_type> n_recovered;
    std::vector<real_type> n_carcass_decay;
    std::vector<real_type> n_emigrate_I;
    std::vector<real_type> p_SI_h_raw;
    std::vector<real_type> births_h;
    std::vector<real_type> n_recovered_h;
    std::vector<real_type> p_SI;
    std::vector<real_type> p_rat_birth_S;
    std::vector<real_type> p_rat_birth_R;
    std::vector<real_type> n_new_carcasses;
    std::vector<real_type> I_flow;
    std::vector<real_type> R_flow;
    std::vector<real_type> p_SI_h;
    std::vector<real_type> n_SI;
    std::vector<real_type> n_births_S;
    std::vector<real_type> n_births_R;
    std::vector<real_type> n_immigrate_I;
    std::vector<real_type> n_immigrate_R;
    std::vector<real_type> n_SI_h;
    std::vector<real_type> n_resistant_births;
    std::vector<real_type> n_emigrate_S;
    std::vector<real_type> n_susceptible_births;
    std::vector<real_type> S_flow;
    std::vector<real_type> n_immigrate_S;
  };
  using data_type = dust2::no_data;
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const int npop = dust2::r::read_int(parameters, "npop", 2);
    const real_type tau = dust2::r::read_real(parameters, "tau", 1);
    const real_type mu_r = dust2::r::read_real(parameters, "mu_r", 0);
    const real_type r_r = dust2::r::read_real(parameters, "r_r", static_cast<real_type>(0.0137));
    const real_type r_h = dust2::r::read_real(parameters, "r_h", static_cast<real_type>(0.00012300000000000001));
    const real_type p = dust2::r::read_real(parameters, "p", static_cast<real_type>(0.97499999999999998));
    const real_type d_r = dust2::r::read_real(parameters, "d_r", static_cast<real_type>(0.00054799999999999998));
    const real_type d_h = dust2::r::read_real(parameters, "d_h", static_cast<real_type>(0.00011));
    const real_type beta_r = dust2::r::read_real(parameters, "beta_r", static_cast<real_type>(0.77000000000000002));
    const real_type beta_h = dust2::r::read_real(parameters, "beta_h", static_cast<real_type>(0.014500000000000001));
    const real_type beta_I = dust2::r::read_real(parameters, "beta_I", 0);
    const real_type rho = dust2::r::read_real(parameters, "rho", static_cast<real_type>(2.6299999999999999));
    const real_type m_r = dust2::r::read_real(parameters, "m_r", static_cast<real_type>(0.056000000000000001));
    const real_type m_h = dust2::r::read_real(parameters, "m_h", static_cast<real_type>(0.125));
    const real_type g_r = dust2::r::read_real(parameters, "g_r", static_cast<real_type>(0.02));
    const real_type g_h = dust2::r::read_real(parameters, "g_h", static_cast<real_type>(0.10000000000000001));
    const real_type delta_R = dust2::r::read_real(parameters, "delta_R", static_cast<real_type>(0.26700000000000002));
    const real_type iota = dust2::r::read_real(parameters, "iota", static_cast<real_type>(0.75));
    const real_type obs_period = dust2::r::read_real(parameters, "obs_period", 1);
    dim.seasonal = dust2::r::read_dimensions<1>(parameters, "seasonal");
    const real_type p_IR = 1 - monty::math::exp<real_type>(-m_r * tau);
    const real_type p_rat_death = 1 - monty::math::exp<real_type>(-d_r * tau);
    const real_type p_migrate_r = 1 - monty::math::exp<real_type>(-mu_r * tau);
    const real_type p_human_death = 1 - monty::math::exp<real_type>(-d_h * tau);
    const real_type birth_rate_h = r_h;
    const real_type p_IR_h = 1 - monty::math::exp<real_type>(-m_h * tau);
    dim.S.set({static_cast<size_t>(npop)});
    dim.I.set({static_cast<size_t>(npop)});
    dim.R.set({static_cast<size_t>(npop)});
    dim.Q.set({static_cast<size_t>(npop)});
    dim.D_r.set({static_cast<size_t>(npop)});
    dim.S_h.set({static_cast<size_t>(npop)});
    dim.I_h.set({static_cast<size_t>(npop)});
    dim.R_h.set({static_cast<size_t>(npop)});
    dim.D_h.set({static_cast<size_t>(npop)});
    dim.T_r.set({static_cast<size_t>(npop)});
    dim.rat_birth_rate_S.set({static_cast<size_t>(npop)});
    dim.rat_birth_rate_R.set({static_cast<size_t>(npop)});
    dim.rat_birth_rate_S_clipped.set({static_cast<size_t>(npop)});
    dim.rat_birth_rate_R_clipped.set({static_cast<size_t>(npop)});
    dim.lambda_r.set({static_cast<size_t>(npop)});
    dim.lambda_h.set({static_cast<size_t>(npop)});
    dim.lambda_hh.set({static_cast<size_t>(npop)});
    dim.p_SI_raw.set({static_cast<size_t>(npop)});
    dim.p_SI.set({static_cast<size_t>(npop)});
    dim.p_SI_h_raw.set({static_cast<size_t>(npop)});
    dim.p_SI_h.set({static_cast<size_t>(npop)});
    dim.p_rat_birth_S.set({static_cast<size_t>(npop)});
    dim.p_rat_birth_R.set({static_cast<size_t>(npop)});
    dim.n_deaths_S.set({static_cast<size_t>(npop)});
    dim.n_deaths_I.set({static_cast<size_t>(npop)});
    dim.n_deaths_R.set({static_cast<size_t>(npop)});
    dim.n_SI.set({static_cast<size_t>(npop)});
    dim.n_IR.set({static_cast<size_t>(npop)});
    dim.n_recovered.set({static_cast<size_t>(npop)});
    dim.n_births_S.set({static_cast<size_t>(npop)});
    dim.n_births_R.set({static_cast<size_t>(npop)});
    dim.n_resistant_births.set({static_cast<size_t>(npop)});
    dim.n_susceptible_births.set({static_cast<size_t>(npop)});
    dim.n_new_carcasses.set({static_cast<size_t>(npop)});
    dim.n_carcass_decay.set({static_cast<size_t>(npop)});
    dim.n_emigrate_S.set({static_cast<size_t>(npop)});
    dim.n_emigrate_I.set({static_cast<size_t>(npop)});
    dim.n_emigrate_R.set({static_cast<size_t>(npop)});
    dim.n_immigrate_S.set({static_cast<size_t>(npop)});
    dim.n_immigrate_I.set({static_cast<size_t>(npop)});
    dim.n_immigrate_R.set({static_cast<size_t>(npop)});
    dim.n_deaths_S_h.set({static_cast<size_t>(npop)});
    dim.n_deaths_I_h.set({static_cast<size_t>(npop)});
    dim.n_deaths_R_h.set({static_cast<size_t>(npop)});
    dim.births_h.set({static_cast<size_t>(npop)});
    dim.n_SI_h.set({static_cast<size_t>(npop)});
    dim.n_IR_h.set({static_cast<size_t>(npop)});
    dim.n_recovered_h.set({static_cast<size_t>(npop)});
    dim.initial_S.set({static_cast<size_t>(npop)});
    dim.initial_S_h.set({static_cast<size_t>(npop)});
    dim.K_r.set({static_cast<size_t>(npop)});
    dim.K_h.set({static_cast<size_t>(npop)});
    dim.I_ini.set({static_cast<size_t>(npop)});
    dim.R_ini.set({static_cast<size_t>(npop)});
    dim.I_h_ini.set({static_cast<size_t>(npop)});
    dim.R_h_ini.set({static_cast<size_t>(npop)});
    dim.contact_r.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    dim.sum_remaining_contact.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    dim.cond_p_r.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    dim.S_flow.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    dim.I_flow.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    dim.R_flow.set({static_cast<size_t>(npop), static_cast<size_t>(npop)});
    std::vector<real_type> seasonal(dim.seasonal.size);
    dust2::r::read_real_array(parameters, dim.seasonal, seasonal.data(), "seasonal", true);
    const real_type birth_rate_h_clipped = (birth_rate_h > 0 ? birth_rate_h : 0);
    std::vector<real_type> contact_r(dim.contact_r.size);
    dust2::r::read_real_array(parameters, dim.contact_r, contact_r.data(), "contact_r", true);
    std::vector<real_type> K_r(dim.K_r.size);
    dust2::r::read_real_array(parameters, dim.K_r, K_r.data(), "K_r", true);
    std::vector<real_type> K_h(dim.K_h.size);
    dust2::r::read_real_array(parameters, dim.K_h, K_h.data(), "K_h", true);
    std::vector<real_type> I_ini(dim.I_ini.size);
    dust2::r::read_real_array(parameters, dim.I_ini, I_ini.data(), "I_ini", true);
    std::vector<real_type> R_ini(dim.R_ini.size);
    dust2::r::read_real_array(parameters, dim.R_ini, R_ini.data(), "R_ini", true);
    std::vector<real_type> I_h_ini(dim.I_h_ini.size);
    dust2::r::read_real_array(parameters, dim.I_h_ini, I_h_ini.data(), "I_h_ini", true);
    std::vector<real_type> R_h_ini(dim.R_h_ini.size);
    dust2::r::read_real_array(parameters, dim.R_h_ini, R_h_ini.data(), "R_h_ini", true);
    std::vector<real_type> sum_remaining_contact(dim.sum_remaining_contact.size);
    for (size_t i = 1; i <= dim.sum_remaining_contact.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.sum_remaining_contact.dim[1]; ++j) {
        sum_remaining_contact[i - 1 + (j - 1) * dim.sum_remaining_contact.mult[1]] = dust2::array::sum<real_type>(contact_r.data(), dim.contact_r, {i - 1, i - 1}, {j - 1, npop - 1});
      }
    }
    const real_type p_human_birth = 1 - monty::math::exp<real_type>(-birth_rate_h_clipped * tau);
    std::vector<real_type> initial_S(dim.initial_S.size);
    for (size_t i = 1; i <= dim.initial_S.size; ++i) {
      initial_S[i - 1] = K_r[i - 1] - I_ini[i - 1] - R_ini[i - 1];
    }
    std::vector<real_type> initial_S_h(dim.initial_S_h.size);
    for (size_t i = 1; i <= dim.initial_S_h.size; ++i) {
      initial_S_h[i - 1] = K_h[i - 1] - I_h_ini[i - 1] - R_h_ini[i - 1];
    }
    std::vector<real_type> cond_p_r(dim.cond_p_r.size);
    for (size_t i = 1; i <= dim.cond_p_r.dim[0]; ++i) {
      for (size_t j = 1; j <= dim.cond_p_r.dim[1]; ++j) {
        cond_p_r[i - 1 + (j - 1) * dim.cond_p_r.mult[1]] = (sum_remaining_contact[i - 1 + (j - 1) * dim.sum_remaining_contact.mult[1]] > 0 ? contact_r[i - 1 + (j - 1) * dim.contact_r.mult[1]] / sum_remaining_contact[i - 1 + (j - 1) * dim.sum_remaining_contact.mult[1]] : 0);
      }
    }
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", std::vector<size_t>(dim.S.dim.begin(), dim.S.dim.end())},
      {"I", std::vector<size_t>(dim.I.dim.begin(), dim.I.dim.end())},
      {"R", std::vector<size_t>(dim.R.dim.begin(), dim.R.dim.end())},
      {"Q", std::vector<size_t>(dim.Q.dim.begin(), dim.Q.dim.end())},
      {"D_r", std::vector<size_t>(dim.D_r.dim.begin(), dim.D_r.dim.end())},
      {"S_h", std::vector<size_t>(dim.S_h.dim.begin(), dim.S_h.dim.end())},
      {"I_h", std::vector<size_t>(dim.I_h.dim.begin(), dim.I_h.dim.end())},
      {"R_h", std::vector<size_t>(dim.R_h.dim.begin(), dim.R_h.dim.end())},
      {"D_h", std::vector<size_t>(dim.D_h.dim.begin(), dim.D_h.dim.end())}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, npop, tau, mu_r, r_r, r_h, p, d_r, d_h, beta_r, beta_h, beta_I, rho, m_r, m_h, g_r, g_h, delta_R, iota, obs_period, p_IR, p_rat_death, p_migrate_r, p_human_death, birth_rate_h, p_IR_h, seasonal, birth_rate_h_clipped, contact_r, K_r, K_h, I_ini, R_ini, I_h_ini, R_h_ini, sum_remaining_contact, p_human_birth, initial_S, initial_S_h, cond_p_r};
  }
  static internal_state build_internal(const shared_state& shared) {
    std::vector<real_type> T_r(shared.dim.T_r.size);
    std::vector<real_type> n_deaths_S(shared.dim.n_deaths_S.size);
    std::vector<real_type> n_deaths_I(shared.dim.n_deaths_I.size);
    std::vector<real_type> n_deaths_R(shared.dim.n_deaths_R.size);
    std::vector<real_type> n_deaths_S_h(shared.dim.n_deaths_S_h.size);
    std::vector<real_type> n_deaths_I_h(shared.dim.n_deaths_I_h.size);
    std::vector<real_type> n_deaths_R_h(shared.dim.n_deaths_R_h.size);
    std::vector<real_type> rat_birth_rate_S(shared.dim.rat_birth_rate_S.size);
    std::vector<real_type> rat_birth_rate_R(shared.dim.rat_birth_rate_R.size);
    std::vector<real_type> lambda_r(shared.dim.lambda_r.size);
    std::vector<real_type> lambda_h(shared.dim.lambda_h.size);
    std::vector<real_type> lambda_hh(shared.dim.lambda_hh.size);
    std::vector<real_type> n_IR(shared.dim.n_IR.size);
    std::vector<real_type> n_emigrate_R(shared.dim.n_emigrate_R.size);
    std::vector<real_type> n_IR_h(shared.dim.n_IR_h.size);
    std::vector<real_type> rat_birth_rate_S_clipped(shared.dim.rat_birth_rate_S_clipped.size);
    std::vector<real_type> rat_birth_rate_R_clipped(shared.dim.rat_birth_rate_R_clipped.size);
    std::vector<real_type> p_SI_raw(shared.dim.p_SI_raw.size);
    std::vector<real_type> n_recovered(shared.dim.n_recovered.size);
    std::vector<real_type> n_carcass_decay(shared.dim.n_carcass_decay.size);
    std::vector<real_type> n_emigrate_I(shared.dim.n_emigrate_I.size);
    std::vector<real_type> p_SI_h_raw(shared.dim.p_SI_h_raw.size);
    std::vector<real_type> births_h(shared.dim.births_h.size);
    std::vector<real_type> n_recovered_h(shared.dim.n_recovered_h.size);
    std::vector<real_type> p_SI(shared.dim.p_SI.size);
    std::vector<real_type> p_rat_birth_S(shared.dim.p_rat_birth_S.size);
    std::vector<real_type> p_rat_birth_R(shared.dim.p_rat_birth_R.size);
    std::vector<real_type> n_new_carcasses(shared.dim.n_new_carcasses.size);
    std::vector<real_type> I_flow(shared.dim.I_flow.size);
    std::vector<real_type> R_flow(shared.dim.R_flow.size);
    std::vector<real_type> p_SI_h(shared.dim.p_SI_h.size);
    std::vector<real_type> n_SI(shared.dim.n_SI.size);
    std::vector<real_type> n_births_S(shared.dim.n_births_S.size);
    std::vector<real_type> n_births_R(shared.dim.n_births_R.size);
    std::vector<real_type> n_immigrate_I(shared.dim.n_immigrate_I.size);
    std::vector<real_type> n_immigrate_R(shared.dim.n_immigrate_R.size);
    std::vector<real_type> n_SI_h(shared.dim.n_SI_h.size);
    std::vector<real_type> n_resistant_births(shared.dim.n_resistant_births.size);
    std::vector<real_type> n_emigrate_S(shared.dim.n_emigrate_S.size);
    std::vector<real_type> n_susceptible_births(shared.dim.n_susceptible_births.size);
    std::vector<real_type> S_flow(shared.dim.S_flow.size);
    std::vector<real_type> n_immigrate_S(shared.dim.n_immigrate_S.size);
    return internal_state{T_r, n_deaths_S, n_deaths_I, n_deaths_R, n_deaths_S_h, n_deaths_I_h, n_deaths_R_h, rat_birth_rate_S, rat_birth_rate_R, lambda_r, lambda_h, lambda_hh, n_IR, n_emigrate_R, n_IR_h, rat_birth_rate_S_clipped, rat_birth_rate_R_clipped, p_SI_raw, n_recovered, n_carcass_decay, n_emigrate_I, p_SI_h_raw, births_h, n_recovered_h, p_SI, p_rat_birth_S, p_rat_birth_R, n_new_carcasses, I_flow, R_flow, p_SI_h, n_SI, n_births_S, n_births_R, n_immigrate_I, n_immigrate_R, n_SI_h, n_resistant_births, n_emigrate_S, n_susceptible_births, S_flow, n_immigrate_S};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.tau = dust2::r::read_real(parameters, "tau", shared.tau);
    shared.mu_r = dust2::r::read_real(parameters, "mu_r", shared.mu_r);
    shared.r_r = dust2::r::read_real(parameters, "r_r", shared.r_r);
    shared.r_h = dust2::r::read_real(parameters, "r_h", shared.r_h);
    shared.p = dust2::r::read_real(parameters, "p", shared.p);
    shared.d_r = dust2::r::read_real(parameters, "d_r", shared.d_r);
    shared.d_h = dust2::r::read_real(parameters, "d_h", shared.d_h);
    shared.beta_r = dust2::r::read_real(parameters, "beta_r", shared.beta_r);
    shared.beta_h = dust2::r::read_real(parameters, "beta_h", shared.beta_h);
    shared.beta_I = dust2::r::read_real(parameters, "beta_I", shared.beta_I);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.m_r = dust2::r::read_real(parameters, "m_r", shared.m_r);
    shared.m_h = dust2::r::read_real(parameters, "m_h", shared.m_h);
    shared.g_r = dust2::r::read_real(parameters, "g_r", shared.g_r);
    shared.g_h = dust2::r::read_real(parameters, "g_h", shared.g_h);
    shared.delta_R = dust2::r::read_real(parameters, "delta_R", shared.delta_R);
    shared.iota = dust2::r::read_real(parameters, "iota", shared.iota);
    shared.obs_period = dust2::r::read_real(parameters, "obs_period", shared.obs_period);
    shared.p_IR = 1 - monty::math::exp<real_type>(-shared.m_r * shared.tau);
    shared.p_rat_death = 1 - monty::math::exp<real_type>(-shared.d_r * shared.tau);
    shared.p_migrate_r = 1 - monty::math::exp<real_type>(-shared.mu_r * shared.tau);
    shared.p_human_death = 1 - monty::math::exp<real_type>(-shared.d_h * shared.tau);
    shared.birth_rate_h = shared.r_h;
    shared.p_IR_h = 1 - monty::math::exp<real_type>(-shared.m_h * shared.tau);
    dust2::r::read_real_array(parameters, shared.dim.seasonal, shared.seasonal.data(), "seasonal", false);
    shared.birth_rate_h_clipped = (shared.birth_rate_h > 0 ? shared.birth_rate_h : 0);
    dust2::r::read_real_array(parameters, shared.dim.contact_r, shared.contact_r.data(), "contact_r", false);
    dust2::r::read_real_array(parameters, shared.dim.K_r, shared.K_r.data(), "K_r", false);
    dust2::r::read_real_array(parameters, shared.dim.K_h, shared.K_h.data(), "K_h", false);
    dust2::r::read_real_array(parameters, shared.dim.I_ini, shared.I_ini.data(), "I_ini", false);
    dust2::r::read_real_array(parameters, shared.dim.R_ini, shared.R_ini.data(), "R_ini", false);
    dust2::r::read_real_array(parameters, shared.dim.I_h_ini, shared.I_h_ini.data(), "I_h_ini", false);
    dust2::r::read_real_array(parameters, shared.dim.R_h_ini, shared.R_h_ini.data(), "R_h_ini", false);
    for (size_t i = 1; i <= shared.dim.sum_remaining_contact.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.sum_remaining_contact.dim[1]; ++j) {
        shared.sum_remaining_contact[i - 1 + (j - 1) * shared.dim.sum_remaining_contact.mult[1]] = dust2::array::sum<real_type>(shared.contact_r.data(), shared.dim.contact_r, {i - 1, i - 1}, {j - 1, shared.npop - 1});
      }
    }
    shared.p_human_birth = 1 - monty::math::exp<real_type>(-shared.birth_rate_h_clipped * shared.tau);
    for (size_t i = 1; i <= shared.dim.initial_S.size; ++i) {
      shared.initial_S[i - 1] = shared.K_r[i - 1] - shared.I_ini[i - 1] - shared.R_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.initial_S_h.size; ++i) {
      shared.initial_S_h[i - 1] = shared.K_h[i - 1] - shared.I_h_ini[i - 1] - shared.R_h_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.cond_p_r.dim[0]; ++i) {
      for (size_t j = 1; j <= shared.dim.cond_p_r.dim[1]; ++j) {
        shared.cond_p_r[i - 1 + (j - 1) * shared.dim.cond_p_r.mult[1]] = (shared.sum_remaining_contact[i - 1 + (j - 1) * shared.dim.sum_remaining_contact.mult[1]] > 0 ? shared.contact_r[i - 1 + (j - 1) * shared.dim.contact_r.mult[1]] / shared.sum_remaining_contact[i - 1 + (j - 1) * shared.dim.sum_remaining_contact.mult[1]] : 0);
      }
    }
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state[i - 1 + 0] = (shared.initial_S[i - 1] > 0 ? shared.initial_S[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.I.size; ++i) {
      state[i - 1 + shared.odin.offset.state[1]] = shared.I_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R.size; ++i) {
      state[i - 1 + shared.odin.offset.state[2]] = shared.R_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Q.size; ++i) {
      state[i - 1 + shared.odin.offset.state[3]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.D_r.size; ++i) {
      state[i - 1 + shared.odin.offset.state[4]] = 0;
    }
    for (size_t i = 1; i <= shared.dim.S_h.size; ++i) {
      state[i - 1 + shared.odin.offset.state[5]] = (shared.initial_S_h[i - 1] > 0 ? shared.initial_S_h[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.I_h.size; ++i) {
      state[i - 1 + shared.odin.offset.state[6]] = shared.I_h_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R_h.size; ++i) {
      state[i - 1 + shared.odin.offset.state[7]] = shared.R_h_ini[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.D_h.size; ++i) {
      state[i - 1 + shared.odin.offset.state[8]] = 0;
    }
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto * S = state + 0;
    const auto * I = state + shared.odin.offset.state[1];
    const auto * R = state + shared.odin.offset.state[2];
    const auto * Q = state + shared.odin.offset.state[3];
    const auto * D_r = state + shared.odin.offset.state[4];
    const auto * S_h = state + shared.odin.offset.state[5];
    const auto * I_h = state + shared.odin.offset.state[6];
    const auto * R_h = state + shared.odin.offset.state[7];
    const auto * D_h = state + shared.odin.offset.state[8];
    for (size_t i = 1; i <= shared.dim.T_r.size; ++i) {
      internal.T_r[i - 1] = S[i - 1] + I[i - 1] + R[i - 1];
    }
    const real_type delta_R_eff = shared.delta_R * shared.seasonal[time + 1 - 1];
    for (size_t i = 1; i <= shared.dim.n_deaths_S.size; ++i) {
      internal.n_deaths_S[i - 1] = monty::random::binomial<real_type>(rng_state, S[i - 1], shared.p_rat_death);
    }
    for (size_t i = 1; i <= shared.dim.n_deaths_I.size; ++i) {
      internal.n_deaths_I[i - 1] = monty::random::binomial<real_type>(rng_state, I[i - 1], shared.p_rat_death);
    }
    for (size_t i = 1; i <= shared.dim.n_deaths_R.size; ++i) {
      internal.n_deaths_R[i - 1] = monty::random::binomial<real_type>(rng_state, R[i - 1], shared.p_rat_death);
    }
    for (size_t i = 1; i <= shared.dim.n_deaths_S_h.size; ++i) {
      internal.n_deaths_S_h[i - 1] = monty::random::binomial<real_type>(rng_state, S_h[i - 1], shared.p_human_death);
    }
    for (size_t i = 1; i <= shared.dim.n_deaths_I_h.size; ++i) {
      internal.n_deaths_I_h[i - 1] = monty::random::binomial<real_type>(rng_state, I_h[i - 1], shared.p_human_death);
    }
    for (size_t i = 1; i <= shared.dim.n_deaths_R_h.size; ++i) {
      internal.n_deaths_R_h[i - 1] = monty::random::binomial<real_type>(rng_state, R_h[i - 1], shared.p_human_death);
    }
    for (size_t i = 1; i <= shared.dim.rat_birth_rate_S.size; ++i) {
      internal.rat_birth_rate_S[i - 1] = shared.r_r * (1 - internal.T_r[i - 1] / shared.K_r[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.rat_birth_rate_R.size; ++i) {
      internal.rat_birth_rate_R[i - 1] = shared.r_r * shared.iota * (1 - internal.T_r[i - 1] / shared.K_r[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.lambda_r.size; ++i) {
      internal.lambda_r[i - 1] = (internal.T_r[i - 1] > 0 ? shared.beta_r * Q[i - 1] * (1 - monty::math::exp<real_type>(-shared.rho * internal.T_r[i - 1] / shared.K_r[i - 1])) / internal.T_r[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.lambda_h.size; ++i) {
      internal.lambda_h[i - 1] = (shared.K_r[i - 1] > 0 ? shared.beta_h * Q[i - 1] * monty::math::exp<real_type>(-shared.rho * internal.T_r[i - 1] / shared.K_r[i - 1]) / shared.K_r[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.lambda_hh.size; ++i) {
      internal.lambda_hh[i - 1] = (shared.K_h[i - 1] > 0 ? shared.beta_I * I_h[i - 1] / shared.K_h[i - 1] : 0);
    }
    const real_type p_carcass_decay = 1 - monty::math::exp<real_type>(-delta_R_eff * shared.tau);
    for (size_t i = 1; i <= shared.dim.n_IR.size; ++i) {
      internal.n_IR[i - 1] = monty::random::binomial<real_type>(rng_state, I[i - 1] - internal.n_deaths_I[i - 1], shared.p_IR);
    }
    for (size_t i = 1; i <= shared.dim.n_emigrate_R.size; ++i) {
      internal.n_emigrate_R[i - 1] = monty::random::binomial<real_type>(rng_state, R[i - 1] - internal.n_deaths_R[i - 1], shared.p_migrate_r);
    }
    for (size_t i = 1; i <= shared.dim.n_IR_h.size; ++i) {
      internal.n_IR_h[i - 1] = monty::random::binomial<real_type>(rng_state, I_h[i - 1] - internal.n_deaths_I_h[i - 1], shared.p_IR_h);
    }
    for (size_t i = 1; i <= shared.dim.rat_birth_rate_S_clipped.size; ++i) {
      internal.rat_birth_rate_S_clipped[i - 1] = (internal.rat_birth_rate_S[i - 1] > 0 ? internal.rat_birth_rate_S[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.rat_birth_rate_R_clipped.size; ++i) {
      internal.rat_birth_rate_R_clipped[i - 1] = (internal.rat_birth_rate_R[i - 1] > 0 ? internal.rat_birth_rate_R[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.p_SI_raw.size; ++i) {
      internal.p_SI_raw[i - 1] = 1 - monty::math::exp<real_type>(-internal.lambda_r[i - 1] * shared.tau);
    }
    for (size_t i = 1; i <= shared.dim.n_recovered.size; ++i) {
      internal.n_recovered[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_IR[i - 1], shared.g_r);
    }
    for (size_t i = 1; i <= shared.dim.n_carcass_decay.size; ++i) {
      internal.n_carcass_decay[i - 1] = monty::random::binomial<real_type>(rng_state, Q[i - 1], p_carcass_decay);
    }
    for (size_t i = 1; i <= shared.dim.n_emigrate_I.size; ++i) {
      internal.n_emigrate_I[i - 1] = monty::random::binomial<real_type>(rng_state, I[i - 1] - internal.n_deaths_I[i - 1] - internal.n_IR[i - 1], shared.p_migrate_r);
    }
    for (size_t i = 1; i <= shared.dim.p_SI_h_raw.size; ++i) {
      internal.p_SI_h_raw[i - 1] = 1 - monty::math::exp<real_type>(-(internal.lambda_h[i - 1] + internal.lambda_hh[i - 1]) * shared.tau);
    }
    for (size_t i = 1; i <= shared.dim.births_h.size; ++i) {
      internal.births_h[i - 1] = monty::random::binomial<real_type>(rng_state, S_h[i - 1] + R_h[i - 1], shared.p_human_birth);
    }
    for (size_t i = 1; i <= shared.dim.n_recovered_h.size; ++i) {
      internal.n_recovered_h[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_IR_h[i - 1], shared.g_h);
    }
    for (size_t i = 1; i <= shared.dim.p_SI.size; ++i) {
      internal.p_SI[i - 1] = (internal.p_SI_raw[i - 1] > 0 ? internal.p_SI_raw[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.p_rat_birth_S.size; ++i) {
      internal.p_rat_birth_S[i - 1] = 1 - monty::math::exp<real_type>(-internal.rat_birth_rate_S_clipped[i - 1] * shared.tau);
    }
    for (size_t i = 1; i <= shared.dim.p_rat_birth_R.size; ++i) {
      internal.p_rat_birth_R[i - 1] = 1 - monty::math::exp<real_type>(-internal.rat_birth_rate_R_clipped[i - 1] * shared.tau);
    }
    for (size_t i = 1; i <= shared.dim.n_new_carcasses.size; ++i) {
      internal.n_new_carcasses[i - 1] = internal.n_IR[i - 1] - internal.n_recovered[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.I_flow.dim[0]; ++i) {
      internal.I_flow[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_I[i - 1], shared.cond_p_r[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.I_flow.dim[0]; ++i) {
      for (size_t j = 2; j <= static_cast<size_t>(shared.npop); ++j) {
        internal.I_flow[i - 1 + (j - 1) * shared.dim.I_flow.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_I[i - 1] - dust2::array::sum<real_type>(internal.I_flow.data(), shared.dim.I_flow, {i - 1, i - 1}, {0, (j - 1) - 1}), shared.cond_p_r[i - 1 + (j - 1) * shared.dim.cond_p_r.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.R_flow.dim[0]; ++i) {
      internal.R_flow[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_R[i - 1], shared.cond_p_r[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.R_flow.dim[0]; ++i) {
      for (size_t j = 2; j <= static_cast<size_t>(shared.npop); ++j) {
        internal.R_flow[i - 1 + (j - 1) * shared.dim.R_flow.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_R[i - 1] - dust2::array::sum<real_type>(internal.R_flow.data(), shared.dim.R_flow, {i - 1, i - 1}, {0, (j - 1) - 1}), shared.cond_p_r[i - 1 + (j - 1) * shared.dim.cond_p_r.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.p_SI_h.size; ++i) {
      internal.p_SI_h[i - 1] = (internal.p_SI_h_raw[i - 1] > 0 ? internal.p_SI_h_raw[i - 1] : 0);
    }
    for (size_t i = 1; i <= shared.dim.n_SI.size; ++i) {
      internal.n_SI[i - 1] = monty::random::binomial<real_type>(rng_state, S[i - 1] - internal.n_deaths_S[i - 1], internal.p_SI[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.n_births_S.size; ++i) {
      internal.n_births_S[i - 1] = monty::random::binomial<real_type>(rng_state, S[i - 1] - internal.n_deaths_S[i - 1], internal.p_rat_birth_S[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.n_births_R.size; ++i) {
      internal.n_births_R[i - 1] = monty::random::binomial<real_type>(rng_state, R[i - 1] - internal.n_deaths_R[i - 1], internal.p_rat_birth_R[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.n_immigrate_I.size; ++i) {
      internal.n_immigrate_I[i - 1] = dust2::array::sum<real_type>(internal.I_flow.data(), shared.dim.I_flow, {0, shared.dim.I_flow.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.n_immigrate_R.size; ++i) {
      internal.n_immigrate_R[i - 1] = dust2::array::sum<real_type>(internal.R_flow.data(), shared.dim.R_flow, {0, shared.dim.R_flow.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.n_SI_h.size; ++i) {
      internal.n_SI_h[i - 1] = monty::random::binomial<real_type>(rng_state, S_h[i - 1] - internal.n_deaths_S_h[i - 1], internal.p_SI_h[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.n_resistant_births.size; ++i) {
      internal.n_resistant_births[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_births_R[i - 1], shared.p);
    }
    for (size_t i = 1; i <= shared.dim.n_emigrate_S.size; ++i) {
      internal.n_emigrate_S[i - 1] = monty::random::binomial<real_type>(rng_state, S[i - 1] - internal.n_deaths_S[i - 1] - internal.n_SI[i - 1], shared.p_migrate_r);
    }
    for (size_t i = 1; i <= shared.dim.n_susceptible_births.size; ++i) {
      internal.n_susceptible_births[i - 1] = internal.n_births_S[i - 1] + internal.n_births_R[i - 1] - internal.n_resistant_births[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.S_flow.dim[0]; ++i) {
      internal.S_flow[i - 1] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_S[i - 1], shared.cond_p_r[i - 1]);
    }
    for (size_t i = 1; i <= shared.dim.S_flow.dim[0]; ++i) {
      for (size_t j = 2; j <= static_cast<size_t>(shared.npop); ++j) {
        internal.S_flow[i - 1 + (j - 1) * shared.dim.S_flow.mult[1]] = monty::random::binomial<real_type>(rng_state, internal.n_emigrate_S[i - 1] - dust2::array::sum<real_type>(internal.S_flow.data(), shared.dim.S_flow, {i - 1, i - 1}, {0, (j - 1) - 1}), shared.cond_p_r[i - 1 + (j - 1) * shared.dim.cond_p_r.mult[1]]);
      }
    }
    for (size_t i = 1; i <= shared.dim.n_immigrate_S.size; ++i) {
      internal.n_immigrate_S[i - 1] = dust2::array::sum<real_type>(internal.S_flow.data(), shared.dim.S_flow, {0, shared.dim.S_flow.dim[0] - 1}, {i - 1, i - 1});
    }
    for (size_t i = 1; i <= shared.dim.S.size; ++i) {
      state_next[i - 1 + 0] = S[i - 1] - internal.n_SI[i - 1] + internal.n_susceptible_births[i - 1] - internal.n_deaths_S[i - 1] - internal.n_emigrate_S[i - 1] + internal.n_immigrate_S[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.I.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[1]] = I[i - 1] + internal.n_SI[i - 1] - internal.n_IR[i - 1] - internal.n_deaths_I[i - 1] - internal.n_emigrate_I[i - 1] + internal.n_immigrate_I[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[2]] = R[i - 1] + internal.n_recovered[i - 1] + internal.n_resistant_births[i - 1] - internal.n_deaths_R[i - 1] - internal.n_emigrate_R[i - 1] + internal.n_immigrate_R[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.Q.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[3]] = Q[i - 1] + internal.n_new_carcasses[i - 1] - internal.n_carcass_decay[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.D_r.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[4]] = (std::fmod(time, shared.obs_period) == 0 ? internal.n_new_carcasses[i - 1] : (D_r[i - 1] + internal.n_new_carcasses[i - 1]));
    }
    for (size_t i = 1; i <= shared.dim.S_h.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[5]] = S_h[i - 1] - internal.n_SI_h[i - 1] + internal.births_h[i - 1] - internal.n_deaths_S_h[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.I_h.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[6]] = I_h[i - 1] + internal.n_SI_h[i - 1] - internal.n_IR_h[i - 1] - internal.n_deaths_I_h[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.R_h.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[7]] = R_h[i - 1] + internal.n_recovered_h[i - 1] - internal.n_deaths_R_h[i - 1];
    }
    for (size_t i = 1; i <= shared.dim.D_h.size; ++i) {
      state_next[i - 1 + shared.odin.offset.state[8]] = (std::fmod(time, shared.obs_period) == 0 ? (internal.n_IR_h[i - 1] - internal.n_recovered_h[i - 1]) : (D_h[i - 1] + internal.n_IR_h[i - 1] - internal.n_recovered_h[i - 1]));
    }
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<plague_stochastic_metapop>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<plague_stochastic_metapop>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<plague_stochastic_metapop>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<plague_stochastic_metapop>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_metapop_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<plague_stochastic_metapop>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}
