// Generated by dust2 (version 0.3.28) - do not edit

// Generated by odin2 (version 0.3.45) - do not edit
#include <dust2/common.hpp>
// [[dust2::class(plague_stochastic_humans)]]
// [[dust2::time_type(discrete)]]
// [[dust2::has_compare()]]
// [[dust2::parameter(tau, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I_ini, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(R_ini, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(K_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(K_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(r_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(r_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(p, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(d_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(d_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(beta_I, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(rho, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(m_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_r, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(g_h, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(delta_R, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(kappa, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(p_obs, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(iota, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(I_h_ini, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(R_h_ini, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(lambda_baseline, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(obs_period, type = "real_type", rank = 0, required = FALSE, constant = FALSE)]]
// [[dust2::parameter(seasonal, type = "real_type", rank = 1, required = TRUE, constant = FALSE)]]
class plague_stochastic_humans {
public:
  plague_stochastic_humans() = delete;
  using real_type = double;
  using rng_state_type = monty::random::generator<real_type>;
  struct shared_state {
    struct odin_internals_type {
      struct {
        dust2::packing state;
      } packing;
      struct {
        std::array<size_t, 9> state;
      } offset;
    } odin;
    struct dim_type {
      dust2::array::dimensions<1> seasonal;
    } dim;
    real_type tau;
    real_type I_ini;
    real_type R_ini;
    real_type K_r;
    real_type K_h;
    real_type r_r;
    real_type r_h;
    real_type p;
    real_type d_r;
    real_type d_h;
    real_type beta_r;
    real_type beta_h;
    real_type beta_I;
    real_type rho;
    real_type m_r;
    real_type m_h;
    real_type g_r;
    real_type g_h;
    real_type delta_R;
    real_type kappa;
    real_type p_obs;
    real_type iota;
    real_type I_h_ini;
    real_type R_h_ini;
    real_type lambda_baseline;
    real_type obs_period;
    real_type p_IR;
    real_type p_rat_death;
    real_type p_human_death;
    real_type birth_rate_h;
    real_type p_IR_h;
    real_type initial_S;
    std::vector<real_type> seasonal;
    real_type birth_rate_h_clipped;
    real_type p_human_birth;
  };
  struct internal_state {};
  struct data_type {
    real_type deaths;
  };
  static dust2::packing packing_state(const shared_state& shared) {
    return shared.odin.packing.state;
  }
  static shared_state build_shared(cpp11::list parameters) {
    shared_state::dim_type dim;
    const real_type tau = dust2::r::read_real(parameters, "tau", 1);
    const real_type I_ini = dust2::r::read_real(parameters, "I_ini", 10);
    const real_type R_ini = dust2::r::read_real(parameters, "R_ini", 0);
    const real_type K_r = dust2::r::read_real(parameters, "K_r", 2500);
    const real_type K_h = dust2::r::read_real(parameters, "K_h", 5000);
    const real_type r_r = dust2::r::read_real(parameters, "r_r", static_cast<real_type>(0.0137));
    const real_type r_h = dust2::r::read_real(parameters, "r_h", static_cast<real_type>(0.00012300000000000001));
    const real_type p = dust2::r::read_real(parameters, "p", static_cast<real_type>(0.97499999999999998));
    const real_type d_r = dust2::r::read_real(parameters, "d_r", static_cast<real_type>(0.00054799999999999998));
    const real_type d_h = dust2::r::read_real(parameters, "d_h", static_cast<real_type>(0.00011));
    const real_type beta_r = dust2::r::read_real(parameters, "beta_r", static_cast<real_type>(0.77000000000000002));
    const real_type beta_h = dust2::r::read_real(parameters, "beta_h", static_cast<real_type>(0.014500000000000001));
    const real_type beta_I = dust2::r::read_real(parameters, "beta_I", 0);
    const real_type rho = dust2::r::read_real(parameters, "rho", static_cast<real_type>(2.6299999999999999));
    const real_type m_r = dust2::r::read_real(parameters, "m_r", static_cast<real_type>(0.056000000000000001));
    const real_type m_h = dust2::r::read_real(parameters, "m_h", static_cast<real_type>(0.125));
    const real_type g_r = dust2::r::read_real(parameters, "g_r", static_cast<real_type>(0.02));
    const real_type g_h = dust2::r::read_real(parameters, "g_h", static_cast<real_type>(0.10000000000000001));
    const real_type delta_R = dust2::r::read_real(parameters, "delta_R", static_cast<real_type>(0.26700000000000002));
    const real_type kappa = dust2::r::read_real(parameters, "kappa", 5);
    const real_type p_obs = dust2::r::read_real(parameters, "p_obs", 1);
    const real_type iota = dust2::r::read_real(parameters, "iota", static_cast<real_type>(0.75));
    const real_type I_h_ini = dust2::r::read_real(parameters, "I_h_ini", 0);
    const real_type R_h_ini = dust2::r::read_real(parameters, "R_h_ini", 0);
    const real_type lambda_baseline = dust2::r::read_real(parameters, "lambda_baseline", 1);
    const real_type obs_period = dust2::r::read_real(parameters, "obs_period", 1);
    dim.seasonal = dust2::r::read_dimensions<1>(parameters, "seasonal");
    const real_type p_IR = 1 - monty::math::exp<real_type>(-m_r * tau);
    const real_type p_rat_death = 1 - monty::math::exp<real_type>(-d_r * tau);
    const real_type p_human_death = 1 - monty::math::exp<real_type>(-d_h * tau);
    const real_type birth_rate_h = r_h;
    const real_type p_IR_h = 1 - monty::math::exp<real_type>(-m_h * tau);
    const real_type initial_S = K_r - I_ini - R_ini;
    std::vector<real_type> seasonal(dim.seasonal.size);
    dust2::r::read_real_array(parameters, dim.seasonal, seasonal.data(), "seasonal", true);
    const real_type birth_rate_h_clipped = (birth_rate_h > 0 ? birth_rate_h : 0);
    const real_type p_human_birth = 1 - monty::math::exp<real_type>(-birth_rate_h_clipped * tau);
    shared_state::odin_internals_type odin;
    odin.packing.state = dust2::packing{
      {"S", {}},
      {"I", {}},
      {"R", {}},
      {"Q", {}},
      {"D_r", {}},
      {"S_h", {}},
      {"I_h", {}},
      {"R_h", {}},
      {"D_h", {}}
    };
    odin.packing.state.copy_offset(odin.offset.state.begin());
    return shared_state{odin, dim, tau, I_ini, R_ini, K_r, K_h, r_r, r_h, p, d_r, d_h, beta_r, beta_h, beta_I, rho, m_r, m_h, g_r, g_h, delta_R, kappa, p_obs, iota, I_h_ini, R_h_ini, lambda_baseline, obs_period, p_IR, p_rat_death, p_human_death, birth_rate_h, p_IR_h, initial_S, seasonal, birth_rate_h_clipped, p_human_birth};
  }
  static internal_state build_internal(const shared_state& shared) {
    return internal_state{};
  }
  static data_type build_data(cpp11::list data, const shared_state& shared) {
    auto deaths = dust2::r::read_real(data, "deaths", NA_REAL);
    return data_type{deaths};
  }
  static void update_shared(cpp11::list parameters, shared_state& shared) {
    shared.tau = dust2::r::read_real(parameters, "tau", shared.tau);
    shared.I_ini = dust2::r::read_real(parameters, "I_ini", shared.I_ini);
    shared.R_ini = dust2::r::read_real(parameters, "R_ini", shared.R_ini);
    shared.K_r = dust2::r::read_real(parameters, "K_r", shared.K_r);
    shared.K_h = dust2::r::read_real(parameters, "K_h", shared.K_h);
    shared.r_r = dust2::r::read_real(parameters, "r_r", shared.r_r);
    shared.r_h = dust2::r::read_real(parameters, "r_h", shared.r_h);
    shared.p = dust2::r::read_real(parameters, "p", shared.p);
    shared.d_r = dust2::r::read_real(parameters, "d_r", shared.d_r);
    shared.d_h = dust2::r::read_real(parameters, "d_h", shared.d_h);
    shared.beta_r = dust2::r::read_real(parameters, "beta_r", shared.beta_r);
    shared.beta_h = dust2::r::read_real(parameters, "beta_h", shared.beta_h);
    shared.beta_I = dust2::r::read_real(parameters, "beta_I", shared.beta_I);
    shared.rho = dust2::r::read_real(parameters, "rho", shared.rho);
    shared.m_r = dust2::r::read_real(parameters, "m_r", shared.m_r);
    shared.m_h = dust2::r::read_real(parameters, "m_h", shared.m_h);
    shared.g_r = dust2::r::read_real(parameters, "g_r", shared.g_r);
    shared.g_h = dust2::r::read_real(parameters, "g_h", shared.g_h);
    shared.delta_R = dust2::r::read_real(parameters, "delta_R", shared.delta_R);
    shared.kappa = dust2::r::read_real(parameters, "kappa", shared.kappa);
    shared.p_obs = dust2::r::read_real(parameters, "p_obs", shared.p_obs);
    shared.iota = dust2::r::read_real(parameters, "iota", shared.iota);
    shared.I_h_ini = dust2::r::read_real(parameters, "I_h_ini", shared.I_h_ini);
    shared.R_h_ini = dust2::r::read_real(parameters, "R_h_ini", shared.R_h_ini);
    shared.lambda_baseline = dust2::r::read_real(parameters, "lambda_baseline", shared.lambda_baseline);
    shared.obs_period = dust2::r::read_real(parameters, "obs_period", shared.obs_period);
    shared.p_IR = 1 - monty::math::exp<real_type>(-shared.m_r * shared.tau);
    shared.p_rat_death = 1 - monty::math::exp<real_type>(-shared.d_r * shared.tau);
    shared.p_human_death = 1 - monty::math::exp<real_type>(-shared.d_h * shared.tau);
    shared.birth_rate_h = shared.r_h;
    shared.p_IR_h = 1 - monty::math::exp<real_type>(-shared.m_h * shared.tau);
    shared.initial_S = shared.K_r - shared.I_ini - shared.R_ini;
    dust2::r::read_real_array(parameters, shared.dim.seasonal, shared.seasonal.data(), "seasonal", false);
    shared.birth_rate_h_clipped = (shared.birth_rate_h > 0 ? shared.birth_rate_h : 0);
    shared.p_human_birth = 1 - monty::math::exp<real_type>(-shared.birth_rate_h_clipped * shared.tau);
  }
  static void update_internal(const shared_state& shared, internal_state& internal) {
  }
  static void initial(real_type time, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state) {
    state[0] = (shared.initial_S > 0 ? shared.initial_S : 0);
    state[1] = shared.I_ini;
    state[2] = shared.R_ini;
    state[3] = 0;
    state[4] = 0;
    state[5] = (shared.K_h > shared.I_h_ini + shared.R_h_ini ? shared.K_h - shared.I_h_ini - shared.R_h_ini : 0);
    state[6] = shared.I_h_ini;
    state[7] = shared.R_h_ini;
    state[8] = 0;
  }
  static void update(real_type time, real_type dt, const real_type* state, const shared_state& shared, internal_state& internal, rng_state_type& rng_state, real_type* state_next) {
    const auto S = state[0];
    const auto I = state[1];
    const auto R = state[2];
    const auto Q = state[3];
    const auto D_r = state[4];
    const auto S_h = state[5];
    const auto I_h = state[6];
    const auto R_h = state[7];
    const auto D_h = state[8];
    const real_type T_r = S + I + R;
    const real_type rat_birth_rate_S = shared.r_r * (1 - T_r / shared.K_r);
    const real_type rat_birth_rate_R = shared.r_r * shared.iota * (1 - T_r / shared.K_r);
    const real_type lambda_r = (T_r > 0 ? shared.beta_r * Q * (1 - monty::math::exp<real_type>(-shared.rho * T_r / shared.K_r)) / T_r : 0);
    const real_type lambda_h = (shared.K_r > 0 ? shared.beta_h * Q * monty::math::exp<real_type>(-shared.rho * T_r / shared.K_r) / shared.K_r : 0);
    const real_type lambda_hh = (shared.K_h > 0 ? shared.beta_I * I_h / shared.K_h : 0);
    const real_type rat_birth_rate_S_clipped = (rat_birth_rate_S > 0 ? rat_birth_rate_S : 0);
    const real_type rat_birth_rate_R_clipped = (rat_birth_rate_R > 0 ? rat_birth_rate_R : 0);
    const real_type delta_R_eff = shared.delta_R * shared.seasonal[time + 1 - 1];
    const real_type p_SI_raw = 1 - monty::math::exp<real_type>(-lambda_r * shared.tau);
    const real_type n_deaths_S = monty::random::binomial<real_type>(rng_state, S, shared.p_rat_death);
    const real_type n_deaths_I = monty::random::binomial<real_type>(rng_state, I, shared.p_rat_death);
    const real_type n_deaths_R = monty::random::binomial<real_type>(rng_state, R, shared.p_rat_death);
    const real_type p_SI_h_raw = 1 - monty::math::exp<real_type>(-(lambda_h + lambda_hh) * shared.tau);
    const real_type n_deaths_S_h = monty::random::binomial<real_type>(rng_state, S_h, shared.p_human_death);
    const real_type n_deaths_I_h = monty::random::binomial<real_type>(rng_state, I_h, shared.p_human_death);
    const real_type n_deaths_R_h = monty::random::binomial<real_type>(rng_state, R_h, shared.p_human_death);
    const real_type p_SI = (p_SI_raw > 0 ? p_SI_raw : 0);
    const real_type p_rat_birth_S = 1 - monty::math::exp<real_type>(-rat_birth_rate_S_clipped * shared.tau);
    const real_type p_rat_birth_R = 1 - monty::math::exp<real_type>(-rat_birth_rate_R_clipped * shared.tau);
    const real_type n_IR = monty::random::binomial<real_type>(rng_state, I - n_deaths_I, shared.p_IR);
    const real_type p_carcass_decay = 1 - monty::math::exp<real_type>(-delta_R_eff * shared.tau);
    const real_type p_SI_h = (p_SI_h_raw > 0 ? p_SI_h_raw : 0);
    const real_type n_IR_h = monty::random::binomial<real_type>(rng_state, I_h - n_deaths_I_h, shared.p_IR_h);
    const real_type n_SI = monty::random::binomial<real_type>(rng_state, S - n_deaths_S, p_SI);
    const real_type n_recovered = monty::random::binomial<real_type>(rng_state, n_IR, shared.g_r);
    const real_type n_births_S = monty::random::binomial<real_type>(rng_state, S - n_deaths_S, p_rat_birth_S);
    const real_type n_births_R = monty::random::binomial<real_type>(rng_state, R - n_deaths_R, p_rat_birth_R);
    const real_type n_carcass_decay = monty::random::binomial<real_type>(rng_state, Q, p_carcass_decay);
    const real_type births_h = monty::random::binomial<real_type>(rng_state, S_h + R_h, shared.p_human_birth);
    const real_type n_SI_h = monty::random::binomial<real_type>(rng_state, S_h - n_deaths_S_h, p_SI_h);
    const real_type n_recovered_h = monty::random::binomial<real_type>(rng_state, n_IR_h, shared.g_h);
    const real_type n_resistant_births = monty::random::binomial<real_type>(rng_state, n_births_R, shared.p);
    const real_type n_new_carcasses = n_IR - n_recovered;
    const real_type n_susceptible_births = n_births_S + n_births_R - n_resistant_births;
    state_next[0] = S - n_SI + n_susceptible_births - n_deaths_S;
    state_next[1] = I + n_SI - n_IR - n_deaths_I;
    state_next[2] = R + n_recovered + n_resistant_births - n_deaths_R;
    state_next[3] = Q + n_new_carcasses - n_carcass_decay;
    state_next[4] = (std::fmod(time, shared.obs_period) == 0 ? n_new_carcasses : (D_r + n_new_carcasses));
    state_next[5] = S_h - n_SI_h + births_h - n_deaths_S_h;
    state_next[6] = I_h + n_SI_h - n_IR_h - n_deaths_I_h;
    state_next[7] = R_h + n_recovered_h - n_deaths_R_h;
    state_next[8] = (std::fmod(time, shared.obs_period) == 0 ? (n_IR_h - n_recovered_h) : (D_h + n_IR_h - n_recovered_h));
  }
  static real_type compare_data(real_type time, const real_type* state, const data_type& data, const shared_state& shared, internal_state& internal, rng_state_type& rng_state) {
    auto unless_nan = [](real_type x) { return std::isnan(x) ? 0 : x; };
    const auto D_h = state[8];
    real_type odin_ll = 0;
    const real_type mu_deaths = shared.p_obs * D_h + shared.lambda_baseline * shared.obs_period;
    odin_ll += unless_nan(monty::density::negative_binomial_mu(data.deaths, shared.kappa, mu_deaths, true));
    return odin_ll;
  }
};

#include <cpp11.hpp>
#include <dust2/r/discrete/system.hpp>
#include <dust2/r/discrete/filter.hpp>
#include <dust2/r/discrete/unfilter.hpp>

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_seed, cpp11::sexp r_deterministic, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_alloc<plague_stochastic_humans>(r_pars, r_time, r_time_control, r_n_particles, r_n_groups, r_seed, r_deterministic, r_n_threads);
}
[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_run_to_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_run_to_time<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_state(cpp11::sexp ptr, cpp11::sexp r_index_state, cpp11::sexp r_index_particle, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_index_state, r_index_particle, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_time(cpp11::sexp ptr) {
  return dust2::r::dust2_system_time<dust2::dust_discrete<plague_stochastic_humans>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_set_state_initial(cpp11::sexp ptr) {
  return dust2::r::dust2_system_set_state_initial<dust2::dust_discrete<plague_stochastic_humans>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_set_state(cpp11::sexp ptr, cpp11::list r_state) {
  return dust2::r::dust2_system_set_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_reorder(cpp11::sexp ptr, cpp11::integers r_index) {
  return dust2::r::dust2_system_reorder<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_index);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_system_rng_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_system_set_rng_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_rng_state);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_set_time(cpp11::sexp ptr, cpp11::sexp r_time) {
  return dust2::r::dust2_system_set_time<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_time);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list pars) {
  return dust2::r::dust2_system_update_pars<dust2::dust_discrete<plague_stochastic_humans>>(ptr, pars);
}

[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_simulate(cpp11::sexp ptr, cpp11::sexp r_times, cpp11::sexp r_index_state, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_simulate<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_times, r_index_state, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads) {
  return dust2::r::dust2_discrete_unfilter_alloc<plague_stochastic_humans>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_alloc(cpp11::list r_pars, cpp11::sexp r_time_start, cpp11::sexp r_time, cpp11::list r_time_control, cpp11::list r_data, cpp11::sexp r_n_particles, cpp11::sexp r_n_groups, cpp11::sexp r_n_threads, cpp11::sexp r_seed) {
  return dust2::r::dust2_discrete_filter_alloc<plague_stochastic_humans>(r_pars, r_time_start, r_time, r_time_control, r_data, r_n_particles, r_n_groups, r_n_threads, r_seed);
}
[[cpp11::register]]
SEXP dust2_system_plague_stochastic_humans_compare_data(cpp11::sexp ptr, cpp11::list r_data, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_system_compare_data<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_data, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_unfilter_update_pars<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp r_index_state, cpp11::sexp r_index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_run<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, r_index_state, r_index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_trajectories<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_snapshots<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_unfilter_plague_stochastic_humans_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_unfilter_last_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_update_pars(cpp11::sexp ptr, cpp11::list r_pars, cpp11::sexp r_index_group) {
  return dust2::r::dust2_filter_update_pars<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_pars, r_index_group);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_run(cpp11::sexp ptr, cpp11::sexp r_initial, bool save_trajectories, cpp11::sexp save_snapshots, bool adjoint, cpp11::sexp index_state, cpp11::sexp index_group, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_run<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_initial, save_trajectories, save_snapshots, adjoint, index_state, index_group, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_last_trajectories(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_trajectories<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_last_snapshots(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_snapshots<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_last_state(cpp11::sexp ptr, bool select_random_particle, bool preserve_particle_dimension, bool preserve_group_dimension) {
  return dust2::r::dust2_filter_last_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, select_random_particle, preserve_particle_dimension, preserve_group_dimension);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_rng_state(cpp11::sexp ptr) {
  return dust2::r::dust2_filter_rng_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr);
}

[[cpp11::register]]
SEXP dust2_filter_plague_stochastic_humans_set_rng_state(cpp11::sexp ptr, cpp11::sexp r_rng_state) {
  return dust2::r::dust2_filter_set_rng_state<dust2::dust_discrete<plague_stochastic_humans>>(ptr, r_rng_state);
}
