# Generated by cpp11: do not edit by hand

dust_plague_stochastic_gpu_info <- function() {
  .Call(`_yersinia_dust_plague_stochastic_gpu_info`)
}

dust_cpu_plague_stochastic_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_plague_stochastic_capabilities <- function() {
  .Call(`_yersinia_dust_cpu_plague_stochastic_capabilities`)
}

dust_cpu_plague_stochastic_run <- function(ptr, r_time_end) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_run`, ptr, r_time_end)
}

dust_cpu_plague_stochastic_simulate <- function(ptr, time_end) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_simulate`, ptr, time_end)
}

dust_cpu_plague_stochastic_run_adjoint <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_run_adjoint`, ptr)
}

dust_cpu_plague_stochastic_set_index <- function(ptr, r_index) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_set_index`, ptr, r_index)
}

dust_cpu_plague_stochastic_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_plague_stochastic_state <- function(ptr, r_index) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_state`, ptr, r_index)
}

dust_cpu_plague_stochastic_time <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_time`, ptr)
}

dust_cpu_plague_stochastic_reorder <- function(ptr, r_index) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_reorder`, ptr, r_index))
}

dust_cpu_plague_stochastic_resample <- function(ptr, r_weights) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_resample`, ptr, r_weights)
}

dust_cpu_plague_stochastic_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_rng_state`, ptr, first_only, last_only)
}

dust_cpu_plague_stochastic_set_rng_state <- function(ptr, rng_state) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_set_rng_state`, ptr, rng_state)
}

dust_cpu_plague_stochastic_set_data <- function(ptr, data, shared) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_set_data`, ptr, data, shared)
}

dust_cpu_plague_stochastic_compare_data <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_compare_data`, ptr)
}

dust_cpu_plague_stochastic_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_plague_stochastic_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_set_n_threads`, ptr, n_threads))
}

dust_cpu_plague_stochastic_n_state <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_n_state`, ptr)
}

dust_cpu_plague_stochastic_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_set_stochastic_schedule`, ptr, time))
}

dust_cpu_plague_stochastic_ode_statistics <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_ode_statistics`, ptr)
}

dust_plague_stochastic_humans_gpu_info <- function() {
  .Call(`_yersinia_dust_plague_stochastic_humans_gpu_info`)
}

dust_cpu_plague_stochastic_humans_alloc <- function(r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_alloc`, r_pars, pars_multi, r_time, r_n_particles, n_threads, r_seed, deterministic, gpu_config, ode_control)
}

dust_cpu_plague_stochastic_humans_capabilities <- function() {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_capabilities`)
}

dust_cpu_plague_stochastic_humans_run <- function(ptr, r_time_end) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_run`, ptr, r_time_end)
}

dust_cpu_plague_stochastic_humans_simulate <- function(ptr, time_end) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_simulate`, ptr, time_end)
}

dust_cpu_plague_stochastic_humans_run_adjoint <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_run_adjoint`, ptr)
}

dust_cpu_plague_stochastic_humans_set_index <- function(ptr, r_index) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_set_index`, ptr, r_index)
}

dust_cpu_plague_stochastic_humans_update_state <- function(ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_update_state`, ptr, r_pars, r_state, r_time, r_set_initial_state, index, reset_step_size)
}

dust_cpu_plague_stochastic_humans_state <- function(ptr, r_index) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_state`, ptr, r_index)
}

dust_cpu_plague_stochastic_humans_time <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_time`, ptr)
}

dust_cpu_plague_stochastic_humans_reorder <- function(ptr, r_index) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_humans_reorder`, ptr, r_index))
}

dust_cpu_plague_stochastic_humans_resample <- function(ptr, r_weights) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_resample`, ptr, r_weights)
}

dust_cpu_plague_stochastic_humans_rng_state <- function(ptr, first_only, last_only) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_rng_state`, ptr, first_only, last_only)
}

dust_cpu_plague_stochastic_humans_set_rng_state <- function(ptr, rng_state) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_set_rng_state`, ptr, rng_state)
}

dust_cpu_plague_stochastic_humans_set_data <- function(ptr, data, shared) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_set_data`, ptr, data, shared)
}

dust_cpu_plague_stochastic_humans_compare_data <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_compare_data`, ptr)
}

dust_cpu_plague_stochastic_humans_filter <- function(ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_filter`, ptr, time_end, save_trajectories, time_snapshot, min_log_likelihood)
}

dust_cpu_plague_stochastic_humans_set_n_threads <- function(ptr, n_threads) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_humans_set_n_threads`, ptr, n_threads))
}

dust_cpu_plague_stochastic_humans_n_state <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_n_state`, ptr)
}

dust_cpu_plague_stochastic_humans_set_stochastic_schedule <- function(ptr, time) {
  invisible(.Call(`_yersinia_dust_cpu_plague_stochastic_humans_set_stochastic_schedule`, ptr, time))
}

dust_cpu_plague_stochastic_humans_ode_statistics <- function(ptr) {
  .Call(`_yersinia_dust_cpu_plague_stochastic_humans_ode_statistics`, ptr)
}
