## Generated by dust2 (version 0.3.28) - do not edit
null_diff_log <- structure(
  function() get("null_diff_log"),
  class = "dust_system_generator",
  name = "null_diff_log",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("tau", "log_I_ini", "R_ini", "K_r", "K_h", "r_r", "r_h", "p", "d_r", "d_h", "log_beta_r", "log_beta_h", "beta_I", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "kappa", "p_obs", "iota", "I_h_ini", "R_h_ini", "log_lambda_baseline", "obs_period"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
    required = c(FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = TRUE),
  default_dt = 1)
null_diff <- structure(
  function() get("null_diff"),
  class = "dust_system_generator",
  name = "null_diff",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("tau", "I_ini", "R_ini", "K_r", "K_h", "r_r", "r_h", "p", "d_r", "d_h", "beta_r", "beta_h", "beta_I", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "kappa", "p_obs", "iota", "I_h_ini", "R_h_ini", "lambda_baseline", "obs_period"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = TRUE),
  default_dt = 1)
plague_ode_min <- structure(
  function() get("plague_ode_min"),
  class = "dust_system_generator",
  name = "plague_ode_min",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("K_r", "K_h", "I_ini", "beta_r", "beta_h", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "kappa", "p_obs", "lambda_baseline", "w_time", "w_value"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L)),
  properties = list(
    time_type = "continuous",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = NULL)
plague_stochastic_humans <- structure(
  function() get("plague_stochastic_humans"),
  class = "dust_system_generator",
  name = "plague_stochastic_humans",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("tau", "I_ini", "R_ini", "K_r", "K_h", "r_r", "r_h", "p", "d_r", "d_h", "beta_r", "beta_h", "beta_I", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "kappa", "p_obs", "iota", "I_h_ini", "R_h_ini", "lambda_baseline", "obs_period", "seasonal", "seasonal_beta"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 1L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
plague_stochastic_metapop <- structure(
  function() get("plague_stochastic_metapop"),
  class = "dust_system_generator",
  name = "plague_stochastic_metapop",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("npop", "tau", "mu_r", "contact_r", "mu_h", "contact_h", "K_r", "K_h", "I_ini", "R_ini", "I_h_ini", "R_h_ini", "r_r", "r_h", "p", "d_r", "d_h", "beta_r", "beta_h", "beta_I", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "iota", "obs_period", "seasonal"),
    type = c("int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    rank = c(0L, 0L, 0L, 2L, 0L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
