## Generated by dust2 (version 0.3.28) - do not edit
plague_stochastic_humans <- structure(
  function() get("plague_stochastic_humans"),
  class = "dust_system_generator",
  name = "plague_stochastic_humans",
  package = "yersinia",
  path = NULL,
  parameters = data.frame(
    name = c("tau", "I_ini", "S_ini", "K_r", "K_h", "r_r", "r_h", "p", "d_r", "d_h", "beta_r", "beta_h", "beta_I", "rho", "m_r", "m_h", "g_r", "g_h", "delta_R", "kappa"),
    type = c("real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    rank = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L)),
  properties = list(
    time_type = "discrete",
    has_compare = TRUE,
    has_adjoint = FALSE),
  default_dt = 1)
